#version 430 core

struct Particle {
    vec3 position;
    vec3 velocity;
};

layout(std430, binding=0) buffer SSBO_0 {
    Particle particles[];
};

//uniform float dt;
uniform float dt;

vec3 vectorField(vec3 p) {
    float r = length(p);
    return vec3(p.y/r, -p.x/r, 0);
}

vec3 calculateForce(Particle particle) {
    vec3 vector = vectorField(particle.position) * 15;
    float magnitude = 15/(pow(length(particle.position)/10, 2));
    vec3 direction = normalize(-particle.position);
    vector += direction * magnitude;

    return vector;
}

void updateParticle(inout Particle particle) {
    // Orbit around 0,0,0
    float magnitude = 5/(pow(length(particle.position)/10, 2));
    vec3 direction = normalize(-particle.position);
    //vec3 force = direction * magnitude;
    vec3 force = calculateForce(particle);

    particle.velocity += force * 0.5 * dt;
    particle.position += particle.velocity * dt;
}

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= particles.length()) return;
    updateParticle(particles[index]);
}